//
// Statio
// Varun Santhanam
//

import ProjectDescription

let config = Config(
    compatibleXcodeVersions: .list(["13.0"]),
    generationOptions: [
        .disableAutogeneratedSchemes,
        .disableSynthesizedResourceAccessors
    ]
)
