//
// Statio
// Varun Santhanam
//

import ProjectDescription

let config = Config(
    compatibleXcodeVersions: .list(["12.5"]),
    generationOptions: [
        .disableAutogeneratedSchemes,
        .disableSynthesizedResourceAccessors
    ]
)
